### ISSUE TITLE
How to enable plugins

### ISSUE THREAD

**Issue by MordyT** [ryanblenis/MeshCentral-RoutePlus#1]
I've read that I need to add this to my config.json

"plugins": {
     enabled: true
},

Every time I do, at the same level as settings or domains, MC crashes on service reload.

If I mod it to be:
"plugins": {
     "enabled": true
},

MC starts and complains about an unknown config option.

Can you provide a screenshot showing where it should be added?
Latest version of MC (0.4.6-u).

**Comment by ryanblenis** [comment]
Hi @MordyT,

If you're adding it at the bottom of your config, you'll want to remove the trailing comma (the last element in valid JSON does not have a trailing comma).

See below for valid examples:

Beginning / middle:
<img width="514" alt="Screen Shot 2019-12-31 at 5 02 46 PM" src="https://user-images.githubusercontent.com/1929277/71635106-98441c00-2bef-11ea-8ebd-4a0828df1f9d.png">

End: 

<img width="1028" alt="Screen Shot 2019-12-31 at 5 03 31 PM" src="https://user-images.githubusercontent.com/1929277/71635110-9bd7a300-2bef-11ea-97ab-1d757bf77cad.png">

**Comment by MordyT** [comment]
Hey!
Got it working.

Your readme needs to be edited so it's "enabled": instead of enabled: (it's currently missing the " around enabled).

Thanks for the quick replies.
