### ISSUE TITLE
RDP link

### ISSUE THREAD

**Issue by coolwormgit** [ryanblenis/MeshCentral-RoutePlus#3]
Hello, can you plz add with check box or somehow when i create a port for my client to select if i want to be created to my account or all others accounts? Because now i have to create the same mappings for each meshlcentral account!

thanks

**Comment by ryanblenis** [comment]
As this is a management interface for "your" forwarded ports, I don't think it is a right fit to add management of other users at this time. Closing this out as `wontfix` - but if there's enough traction for requests like this in the future it may be revisited. Thank you.
