### ISSUE TITLE
Source Port: 0 

### ISSUE THREAD

**Issue by coolwormgit** [ryanblenis/MeshCentral-RoutePlus#4]
After update when i add client i get source port : 0

![Untitled](https://user-images.githubusercontent.com/10504401/71667631-98b6f100-2d6e-11ea-8136-2239d963a261.jpg)

**Comment by ryanblenis** [comment]
Hi @coolwormgit,

The source port is reported once "Your" computer has assigned a port. Is the "My Computer" you've designated at the top of that screen online? If not, that is the issue.

If it is (and the MeshCentral agent is running as expected), what OS is it running so I can run some tests? If there is any other info you can give to reproduce this it would be helpful, as I cannot reproduce it with the given data. Thank you.

**Comment by coolwormgit** [comment]
ok!! for some reason lost my computer and i didnt realize that!! that was the proplem!! thanka
