### ISSUE TITLE
Cannot locate debug file routeplus.txt

### ISSUE THREAD

**Issue by dhunt84971** [ryanblenis/MeshCentral-RoutePlus#8]
Hi @ryanblenis ,

I've enabled debug so I can troubleshoot some connectivity issues I seem to be having, but after setting debug_flag = true I have been unable to locate the routeplus.txt file.

[MeshCentral 5.1j on Ubuntu 18.04]

Any help is appreciated.

**Comment by ryanblenis** [comment]
It is located in the MeshAgent directory.

On a Linux client this is: /usr/local/mesh

**Comment by dhunt84971** [comment]
For some reason this seems to be located in the root.  This is the agent I am running on the server box so maybe that has something to do with it?
![Screenshot from 2020-04-09 13-43-49](https://user-images.githubusercontent.com/674065/78924701-47528800-7a68-11ea-976d-3b4a73c28140.png)

**Comment by ryanblenis** [comment]
Interestingly, I see the same thing on my Linux boxes. The file just writes to the current working directory, which (up until recently) was the aforementioned path.

I'll have to check with the MeshCentral guys to see what changed and why, but basically if you log into a "Terminal" session and type `pwd` that is where it will end up. (Posted on main project `[here](https://github.com/Ylianst/MeshCentral/issues/1134)`)

**Comment by ryanblenis** [comment]
From some other input on that ticket, it appears that is a base MC issue. Closing this out so it can be handled over there.

**Comment by ryanblenis** [comment]
Noting here that this was fixed in the last commit (but not yet on a new version, along with manual fix here: https://github.com/Ylianst/MeshCentral/issues/1134)
