### ISSUE TITLE
Disconnects when click on RoutePlus RDP and page refresh

### ISSUE THREAD

**Issue by uldiseihenbergs** [ryanblenis/MeshCentral-RoutePlus#9]
i'm crossposting from here: https://github.com/Ylianst/MeshCentral/issues/1156
when i click on RoutePlus RDP on devices page, download starts, but web page says Disconected:
![image](https://user-images.githubusercontent.com/60253253/79839088-b0b58d80-83bc-11ea-98a0-ce42a1a3e735.png)
![image](https://user-images.githubusercontent.com/60253253/79839116-bad78c00-83bc-11ea-8881-ad7482bf417a.png)

and one more thing - when you add or remove port mapping, and then open up a device, "RoutePlus RDP" is not ther or still in place according you add or remove - when you do a full page refresh with Ctrl+Shift+R, then it appers/disappears accordingly. i think, it should work without full refresh.

and i'm on Ubuntu desktop with Google Chrome browser. MC version 0.5.7. and yes, error  occurs every time, i just tested again.

**Comment by ryanblenis** [comment]
I couldn't recreate it with Chrome - but looking at your screenshot actually has the Firefox logo, which I can re-create the issue with. Working on this now. Thanks for the report.

**Comment by ryanblenis** [comment]
The RDP download issue and "RoutePlus RDP" link display issues have been fixed in v0.1.3

Thank you.

**Comment by uldiseihenbergs** [comment]
@ryanblenis thanks for your work, but i can't upgrade your plugin - it says it's incompatible with MC, but i'm on MC stable - 0.5.7 know..

**Comment by ryanblenis** [comment]
0.5.4-8 broke the plugin system version compatibility detection. Once you upgrade MeshCentral you'll be able to upgrade the plugin.

**Comment by uldiseihenbergs** [comment]
maybe it's time to ask Ylianst to mark new version as stable?

**Comment by ryanblenis** [comment]
Yeah, given the new versioning changes and stable / latest tags, I'm not sure that he's quite separated channels out of the master branch for stable (bug fixes) and non-stable (feature addition) releases yet- so I'm not sure those tags will carry much weight until that happens.

**Comment by uldiseihenbergs** [comment]
that's true, i think branch is one. can you ask him to mark new stable version because of this version thing?

**Comment by ryanblenis** [comment]
MC stable version has been bumped.
